language: node_js

node_js:
  - "12"

#before_deploy:
#  - npm run prepare
#  - npm run predeploy
#  - npm version patch
jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: release
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        script: "npx semantic-release"
        skip_cleanup: true
    - stage: release-example-app
      node_js: lts/*
      before_deploy:
        - npm run predeploy
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        keep_history: true
        local_dir: "example/build"
        on:
          branch: master
stages:
  - release
  - release-example-app
#  - provider: npm
#    email: "$NPM_EMAIL"
#    api_key: "$NPM_AUTH_TOKEN"
#    skip_cleanup: true
#    on:
#      branch: master
#
#  - provider: pages
#    skip_cleanup: true
#    github_token: "$GITHUB_TOKEN"
#    keep_history: true
#    local_dir: "example/build"
#    on:
#      branch: master
